// GENERATED by scripts/gen_conformance_tests.py from protocol/methods.json.
// DO NOT EDIT BY HAND — regenerate instead. Coverage is enforced by
// scripts/check_conformance.py (G3).

import XCTest
@testable import HermesKit

/// One canonical round-trip per catalog entry: encode → decode → equal.
final class ProtocolConformanceTests: XCTestCase {
    private let codec = WireCodec()

    private func assertRoundTrip(
        _ kind: String, name: String, id: JSONRPCID?, file: StaticString = #filePath, line: UInt = #line
    ) throws {
        var envelope = JSONRPCEnvelope(method: name)
        envelope.id = id
        envelope.params = .object(["__probe": .string(name)])
        let data = try codec.encode(envelope)
        let decoded = try codec.decode(data)
        XCTAssertEqual(decoded.method, name, "\(kind) \(name) lost its name", file: file, line: line)
        XCTAssertEqual(decoded.params?["__probe"], .string(name), file: file, line: line)
        let again = try codec.decode(try codec.encode(decoded))
        XCTAssertEqual(again, decoded, "\(kind) \(name) not a fixed point", file: file, line: line)
    }

    func testM_AgentsList() throws {
        try assertRoundTrip("method", name: "agents.list", id: .int(1))
    }

    func testM_ApprovalPending() throws {
        try assertRoundTrip("method", name: "approval.pending", id: .int(1))
    }

    func testM_ApprovalReceived() throws {
        try assertRoundTrip("method", name: "approval.received", id: .int(1))
    }

    func testM_ApprovalRespond() throws {
        try assertRoundTrip("method", name: "approval.respond", id: .int(1))
    }

    func testM_BillingAuto_reload() throws {
        try assertRoundTrip("method", name: "billing.auto_reload", id: .int(1))
    }

    func testM_BillingCharge() throws {
        try assertRoundTrip("method", name: "billing.charge", id: .int(1))
    }

    func testM_BillingCharge_status() throws {
        try assertRoundTrip("method", name: "billing.charge_status", id: .int(1))
    }

    func testM_BillingState() throws {
        try assertRoundTrip("method", name: "billing.state", id: .int(1))
    }

    func testM_BillingStep_up() throws {
        try assertRoundTrip("method", name: "billing.step_up", id: .int(1))
    }

    func testM_Bot_relayDeliver() throws {
        try assertRoundTrip("method", name: "bot_relay.deliver", id: .int(1))
    }

    func testM_Bot_relayOutboxDrain() throws {
        try assertRoundTrip("method", name: "bot_relay.outbox.drain", id: .int(1))
    }

    func testM_Bot_relayReply() throws {
        try assertRoundTrip("method", name: "bot_relay.reply", id: .int(1))
    }

    func testM_Bot_relayRosterSync() throws {
        try assertRoundTrip("method", name: "bot_relay.roster.sync", id: .int(1))
    }

    func testM_BrowserControllerDetach() throws {
        try assertRoundTrip("method", name: "browser.controller.detach", id: .int(1))
    }

    func testM_BrowserControllerHeartbeat() throws {
        try assertRoundTrip("method", name: "browser.controller.heartbeat", id: .int(1))
    }

    func testM_BrowserControllerRegister() throws {
        try assertRoundTrip("method", name: "browser.controller.register", id: .int(1))
    }

    func testM_BrowserControllerResult() throws {
        try assertRoundTrip("method", name: "browser.controller.result", id: .int(1))
    }

    func testM_BrowserManage() throws {
        try assertRoundTrip("method", name: "browser.manage", id: .int(1))
    }

    func testM_ClarifyRespond() throws {
        try assertRoundTrip("method", name: "clarify.respond", id: .int(1))
    }

    func testM_CliExec() throws {
        try assertRoundTrip("method", name: "cli.exec", id: .int(1))
    }

    func testM_ClipboardPaste() throws {
        try assertRoundTrip("method", name: "clipboard.paste", id: .int(1))
    }

    func testM_CommandDispatch() throws {
        try assertRoundTrip("method", name: "command.dispatch", id: .int(1))
    }

    func testM_CommandResolve() throws {
        try assertRoundTrip("method", name: "command.resolve", id: .int(1))
    }

    func testM_CommandsCatalog() throws {
        try assertRoundTrip("method", name: "commands.catalog", id: .int(1))
    }

    func testM_CompletePath() throws {
        try assertRoundTrip("method", name: "complete.path", id: .int(1))
    }

    func testM_CompleteSlash() throws {
        try assertRoundTrip("method", name: "complete.slash", id: .int(1))
    }

    func testM_ConfigGet() throws {
        try assertRoundTrip("method", name: "config.get", id: .int(1))
    }

    func testM_ConfigSet() throws {
        try assertRoundTrip("method", name: "config.set", id: .int(1))
    }

    func testM_ConfigShow() throws {
        try assertRoundTrip("method", name: "config.show", id: .int(1))
    }

    func testM_CronManage() throws {
        try assertRoundTrip("method", name: "cron.manage", id: .int(1))
    }

    func testM_DelegationPause() throws {
        try assertRoundTrip("method", name: "delegation.pause", id: .int(1))
    }

    func testM_DelegationStatus() throws {
        try assertRoundTrip("method", name: "delegation.status", id: .int(1))
    }

    func testM_DiagnosticsShare_nous() throws {
        try assertRoundTrip("method", name: "diagnostics.share_nous", id: .int(1))
    }

    func testM_FileAttach() throws {
        try assertRoundTrip("method", name: "file.attach", id: .int(1))
    }

    func testM_HandoffFail() throws {
        try assertRoundTrip("method", name: "handoff.fail", id: .int(1))
    }

    func testM_HandoffRequest() throws {
        try assertRoundTrip("method", name: "handoff.request", id: .int(1))
    }

    func testM_HandoffState() throws {
        try assertRoundTrip("method", name: "handoff.state", id: .int(1))
    }

    func testM_ImageAttach() throws {
        try assertRoundTrip("method", name: "image.attach", id: .int(1))
    }

    func testM_ImageAttach_bytes() throws {
        try assertRoundTrip("method", name: "image.attach_bytes", id: .int(1))
    }

    func testM_ImageDetach() throws {
        try assertRoundTrip("method", name: "image.detach", id: .int(1))
    }

    func testM_ImageGenerate() throws {
        try assertRoundTrip("method", name: "image.generate", id: .int(1))
    }

    func testM_InputDetect_drop() throws {
        try assertRoundTrip("method", name: "input.detect_drop", id: .int(1))
    }

    func testM_InsightsGet() throws {
        try assertRoundTrip("method", name: "insights.get", id: .int(1))
    }

    func testM_LearningDelete() throws {
        try assertRoundTrip("method", name: "learning.delete", id: .int(1))
    }

    func testM_LearningDetail() throws {
        try assertRoundTrip("method", name: "learning.detail", id: .int(1))
    }

    func testM_LearningEdit() throws {
        try assertRoundTrip("method", name: "learning.edit", id: .int(1))
    }

    func testM_LearningFrames() throws {
        try assertRoundTrip("method", name: "learning.frames", id: .int(1))
    }

    func testM_LlmOneshot() throws {
        try assertRoundTrip("method", name: "llm.oneshot", id: .int(1))
    }

    func testM_McpCatalog() throws {
        try assertRoundTrip("method", name: "mcp.catalog", id: .int(1))
    }

    func testM_McpServersAdd() throws {
        try assertRoundTrip("method", name: "mcp.servers.add", id: .int(1))
    }

    func testM_McpServersList() throws {
        try assertRoundTrip("method", name: "mcp.servers.list", id: .int(1))
    }

    func testM_McpServersOauthPoll() throws {
        try assertRoundTrip("method", name: "mcp.servers.oauth.poll", id: .int(1))
    }

    func testM_McpServersOauthStart() throws {
        try assertRoundTrip("method", name: "mcp.servers.oauth.start", id: .int(1))
    }

    func testM_McpServersRemove() throws {
        try assertRoundTrip("method", name: "mcp.servers.remove", id: .int(1))
    }

    func testM_McpServersSet_api_key() throws {
        try assertRoundTrip("method", name: "mcp.servers.set_api_key", id: .int(1))
    }

    func testM_McpServersTest() throws {
        try assertRoundTrip("method", name: "mcp.servers.test", id: .int(1))
    }

    func testM_McpSetupRespond() throws {
        try assertRoundTrip("method", name: "mcp.setup.respond", id: .int(1))
    }

    func testM_MessageReact() throws {
        try assertRoundTrip("method", name: "message.react", id: .int(1))
    }

    func testM_ModelDisconnect() throws {
        try assertRoundTrip("method", name: "model.disconnect", id: .int(1))
    }

    func testM_ModelOptions() throws {
        try assertRoundTrip("method", name: "model.options", id: .int(1))
    }

    func testM_ModelSave_key() throws {
        try assertRoundTrip("method", name: "model.save_key", id: .int(1))
    }

    func testM_PasteCollapse() throws {
        try assertRoundTrip("method", name: "paste.collapse", id: .int(1))
    }

    func testM_PdfAttach() throws {
        try assertRoundTrip("method", name: "pdf.attach", id: .int(1))
    }

    func testM_PetCancel() throws {
        try assertRoundTrip("method", name: "pet.cancel", id: .int(1))
    }

    func testM_PetCells() throws {
        try assertRoundTrip("method", name: "pet.cells", id: .int(1))
    }

    func testM_PetDisable() throws {
        try assertRoundTrip("method", name: "pet.disable", id: .int(1))
    }

    func testM_PetExport() throws {
        try assertRoundTrip("method", name: "pet.export", id: .int(1))
    }

    func testM_PetGallery() throws {
        try assertRoundTrip("method", name: "pet.gallery", id: .int(1))
    }

    func testM_PetGenerate() throws {
        try assertRoundTrip("method", name: "pet.generate", id: .int(1))
    }

    func testM_PetGenerateStatus() throws {
        try assertRoundTrip("method", name: "pet.generate.status", id: .int(1))
    }

    func testM_PetHatch() throws {
        try assertRoundTrip("method", name: "pet.hatch", id: .int(1))
    }

    func testM_PetInfo() throws {
        try assertRoundTrip("method", name: "pet.info", id: .int(1))
    }

    func testM_PetInfoMeta() throws {
        try assertRoundTrip("method", name: "pet.info.meta", id: .int(1))
    }

    func testM_PetRemove() throws {
        try assertRoundTrip("method", name: "pet.remove", id: .int(1))
    }

    func testM_PetRename() throws {
        try assertRoundTrip("method", name: "pet.rename", id: .int(1))
    }

    func testM_PetScale() throws {
        try assertRoundTrip("method", name: "pet.scale", id: .int(1))
    }

    func testM_PetSelect() throws {
        try assertRoundTrip("method", name: "pet.select", id: .int(1))
    }

    func testM_PetThumb() throws {
        try assertRoundTrip("method", name: "pet.thumb", id: .int(1))
    }

    func testM_Ping() throws {
        try assertRoundTrip("method", name: "ping", id: .int(1))
    }

    func testM_PluginsList() throws {
        try assertRoundTrip("method", name: "plugins.list", id: .int(1))
    }

    func testM_PluginsManage() throws {
        try assertRoundTrip("method", name: "plugins.manage", id: .int(1))
    }

    func testM_PreviewActRespond() throws {
        try assertRoundTrip("method", name: "preview.act.respond", id: .int(1))
    }

    func testM_PreviewReadRespond() throws {
        try assertRoundTrip("method", name: "preview.read.respond", id: .int(1))
    }

    func testM_PreviewRestart() throws {
        try assertRoundTrip("method", name: "preview.restart", id: .int(1))
    }

    func testM_ProcessKill() throws {
        try assertRoundTrip("method", name: "process.kill", id: .int(1))
    }

    func testM_ProcessList() throws {
        try assertRoundTrip("method", name: "process.list", id: .int(1))
    }

    func testM_ProcessStop() throws {
        try assertRoundTrip("method", name: "process.stop", id: .int(1))
    }

    func testM_ProfilesConfigure() throws {
        try assertRoundTrip("method", name: "profiles.configure", id: .int(1))
    }

    func testM_ProfilesCreate() throws {
        try assertRoundTrip("method", name: "profiles.create", id: .int(1))
    }

    func testM_ProfilesDescribe() throws {
        try assertRoundTrip("method", name: "profiles.describe", id: .int(1))
    }

    func testM_ProfilesGet_asset() throws {
        try assertRoundTrip("method", name: "profiles.get_asset", id: .int(1))
    }

    func testM_ProfilesList() throws {
        try assertRoundTrip("method", name: "profiles.list", id: .int(1))
    }

    func testM_ProfilesSet_asset() throws {
        try assertRoundTrip("method", name: "profiles.set_asset", id: .int(1))
    }

    func testM_ProjectFacts() throws {
        try assertRoundTrip("method", name: "project.facts", id: .int(1))
    }

    func testM_ProjectsDiscover_repos() throws {
        try assertRoundTrip("method", name: "projects.discover_repos", id: .int(1))
    }

    func testM_ProjectsProject_sessions() throws {
        try assertRoundTrip("method", name: "projects.project_sessions", id: .int(1))
    }

    func testM_ProjectsRecord_repos() throws {
        try assertRoundTrip("method", name: "projects.record_repos", id: .int(1))
    }

    func testM_ProjectsTree() throws {
        try assertRoundTrip("method", name: "projects.tree", id: .int(1))
    }

    func testM_PromptBackground() throws {
        try assertRoundTrip("method", name: "prompt.background", id: .int(1))
    }

    func testM_PromptSubmit() throws {
        try assertRoundTrip("method", name: "prompt.submit", id: .int(1))
    }

    func testM_ReloadEnv() throws {
        try assertRoundTrip("method", name: "reload.env", id: .int(1))
    }

    func testM_ReloadMcp() throws {
        try assertRoundTrip("method", name: "reload.mcp", id: .int(1))
    }

    func testM_RollbackDiff() throws {
        try assertRoundTrip("method", name: "rollback.diff", id: .int(1))
    }

    func testM_RollbackList() throws {
        try assertRoundTrip("method", name: "rollback.list", id: .int(1))
    }

    func testM_RollbackRestore() throws {
        try assertRoundTrip("method", name: "rollback.restore", id: .int(1))
    }

    func testM_SecretRespond() throws {
        try assertRoundTrip("method", name: "secret.respond", id: .int(1))
    }

    func testM_SessionActivate() throws {
        try assertRoundTrip("method", name: "session.activate", id: .int(1))
    }

    func testM_SessionActive_list() throws {
        try assertRoundTrip("method", name: "session.active_list", id: .int(1))
    }

    func testM_SessionBranch() throws {
        try assertRoundTrip("method", name: "session.branch", id: .int(1))
    }

    func testM_SessionClose() throws {
        try assertRoundTrip("method", name: "session.close", id: .int(1))
    }

    func testM_SessionCompress() throws {
        try assertRoundTrip("method", name: "session.compress", id: .int(1))
    }

    func testM_SessionContext_breakdown() throws {
        try assertRoundTrip("method", name: "session.context_breakdown", id: .int(1))
    }

    func testM_SessionCreate() throws {
        try assertRoundTrip("method", name: "session.create", id: .int(1))
    }

    func testM_SessionCwdSet() throws {
        try assertRoundTrip("method", name: "session.cwd.set", id: .int(1))
    }

    func testM_SessionDelete() throws {
        try assertRoundTrip("method", name: "session.delete", id: .int(1))
    }

    func testM_SessionEventsSince() throws {
        try assertRoundTrip("method", name: "session.events.since", id: .int(1))
    }

    func testM_SessionEventsStats() throws {
        try assertRoundTrip("method", name: "session.events.stats", id: .int(1))
    }

    func testM_SessionHistory() throws {
        try assertRoundTrip("method", name: "session.history", id: .int(1))
    }

    func testM_SessionInterrupt() throws {
        try assertRoundTrip("method", name: "session.interrupt", id: .int(1))
    }

    func testM_SessionList() throws {
        try assertRoundTrip("method", name: "session.list", id: .int(1))
    }

    func testM_SessionMost_recent() throws {
        try assertRoundTrip("method", name: "session.most_recent", id: .int(1))
    }

    func testM_SessionRedirect() throws {
        try assertRoundTrip("method", name: "session.redirect", id: .int(1))
    }

    func testM_SessionResume() throws {
        try assertRoundTrip("method", name: "session.resume", id: .int(1))
    }

    func testM_SessionSave() throws {
        try assertRoundTrip("method", name: "session.save", id: .int(1))
    }

    func testM_SessionSet_hidden() throws {
        try assertRoundTrip("method", name: "session.set_hidden", id: .int(1))
    }

    func testM_SessionStatus() throws {
        try assertRoundTrip("method", name: "session.status", id: .int(1))
    }

    func testM_SessionSteer() throws {
        try assertRoundTrip("method", name: "session.steer", id: .int(1))
    }

    func testM_SessionTitle() throws {
        try assertRoundTrip("method", name: "session.title", id: .int(1))
    }

    func testM_SessionUndo() throws {
        try assertRoundTrip("method", name: "session.undo", id: .int(1))
    }

    func testM_SessionUsage() throws {
        try assertRoundTrip("method", name: "session.usage", id: .int(1))
    }

    func testM_SessionWorkspaceMove() throws {
        try assertRoundTrip("method", name: "session.workspace.move", id: .int(1))
    }

    func testM_SetupRuntime_check() throws {
        try assertRoundTrip("method", name: "setup.runtime_check", id: .int(1))
    }

    func testM_SetupStatus() throws {
        try assertRoundTrip("method", name: "setup.status", id: .int(1))
    }

    func testM_ShellExec() throws {
        try assertRoundTrip("method", name: "shell.exec", id: .int(1))
    }

    func testM_SkillsManage() throws {
        try assertRoundTrip("method", name: "skills.manage", id: .int(1))
    }

    func testM_SkillsReload() throws {
        try assertRoundTrip("method", name: "skills.reload", id: .int(1))
    }

    func testM_SlashExec() throws {
        try assertRoundTrip("method", name: "slash.exec", id: .int(1))
    }

    func testM_Spawn_treeList() throws {
        try assertRoundTrip("method", name: "spawn_tree.list", id: .int(1))
    }

    func testM_Spawn_treeLoad() throws {
        try assertRoundTrip("method", name: "spawn_tree.load", id: .int(1))
    }

    func testM_Spawn_treeSave() throws {
        try assertRoundTrip("method", name: "spawn_tree.save", id: .int(1))
    }

    func testM_SubagentInterrupt() throws {
        try assertRoundTrip("method", name: "subagent.interrupt", id: .int(1))
    }

    func testM_SubagentSteer() throws {
        try assertRoundTrip("method", name: "subagent.steer", id: .int(1))
    }

    func testM_SubscriptionChange() throws {
        try assertRoundTrip("method", name: "subscription.change", id: .int(1))
    }

    func testM_SubscriptionPreview() throws {
        try assertRoundTrip("method", name: "subscription.preview", id: .int(1))
    }

    func testM_SubscriptionResume() throws {
        try assertRoundTrip("method", name: "subscription.resume", id: .int(1))
    }

    func testM_SubscriptionState() throws {
        try assertRoundTrip("method", name: "subscription.state", id: .int(1))
    }

    func testM_SubscriptionUpgrade() throws {
        try assertRoundTrip("method", name: "subscription.upgrade", id: .int(1))
    }

    func testM_SudoRespond() throws {
        try assertRoundTrip("method", name: "sudo.respond", id: .int(1))
    }

    func testM_SystemBattery() throws {
        try assertRoundTrip("method", name: "system.battery", id: .int(1))
    }

    func testM_TerminalReadRespond() throws {
        try assertRoundTrip("method", name: "terminal.read.respond", id: .int(1))
    }

    func testM_TerminalResize() throws {
        try assertRoundTrip("method", name: "terminal.resize", id: .int(1))
    }

    func testM_ToolsConfigure() throws {
        try assertRoundTrip("method", name: "tools.configure", id: .int(1))
    }

    func testM_ToolsList() throws {
        try assertRoundTrip("method", name: "tools.list", id: .int(1))
    }

    func testM_ToolsShow() throws {
        try assertRoundTrip("method", name: "tools.show", id: .int(1))
    }

    func testM_ToolsetsList() throws {
        try assertRoundTrip("method", name: "toolsets.list", id: .int(1))
    }

    func testM_TourRespond() throws {
        try assertRoundTrip("method", name: "tour.respond", id: .int(1))
    }

    func testM_UsageBars() throws {
        try assertRoundTrip("method", name: "usage.bars", id: .int(1))
    }

    func testM_VerificationStatus() throws {
        try assertRoundTrip("method", name: "verification.status", id: .int(1))
    }

    func testM_VoiceRecord() throws {
        try assertRoundTrip("method", name: "voice.record", id: .int(1))
    }

    func testM_VoiceToggle() throws {
        try assertRoundTrip("method", name: "voice.toggle", id: .int(1))
    }

    func testM_VoiceTts() throws {
        try assertRoundTrip("method", name: "voice.tts", id: .int(1))
    }

    func testM_WakeFeed() throws {
        try assertRoundTrip("method", name: "wake.feed", id: .int(1))
    }

    func testM_WakePause() throws {
        try assertRoundTrip("method", name: "wake.pause", id: .int(1))
    }

    func testM_WakeResume() throws {
        try assertRoundTrip("method", name: "wake.resume", id: .int(1))
    }

    func testM_WakeStart() throws {
        try assertRoundTrip("method", name: "wake.start", id: .int(1))
    }

    func testM_WakeStatus() throws {
        try assertRoundTrip("method", name: "wake.status", id: .int(1))
    }

    func testM_WakeStop() throws {
        try assertRoundTrip("method", name: "wake.stop", id: .int(1))
    }

    func testM_WindowReadRespond() throws {
        try assertRoundTrip("method", name: "window.read.respond", id: .int(1))
    }

    func testE_AgentTerminalOutput() throws {
        try assertRoundTrip("event", name: "agent.terminal.output", id: nil)
    }

    func testE_ApprovalRequest() throws {
        try assertRoundTrip("event", name: "approval.request", id: nil)
    }

    func testE_BackgroundComplete() throws {
        try assertRoundTrip("event", name: "background.complete", id: nil)
    }

    func testE_BillingStep_upVerification() throws {
        try assertRoundTrip("event", name: "billing.step_up.verification", id: nil)
    }

    func testE_BrowserProgress() throws {
        try assertRoundTrip("event", name: "browser.progress", id: nil)
    }

    func testE_ClarifyExpire() throws {
        try assertRoundTrip("event", name: "clarify.expire", id: nil)
    }

    func testE_ClarifyRequest() throws {
        try assertRoundTrip("event", name: "clarify.request", id: nil)
    }

    func testE_Error() throws {
        try assertRoundTrip("event", name: "error", id: nil)
    }

    func testE_GatewayReady() throws {
        try assertRoundTrip("event", name: "gateway.ready", id: nil)
    }

    func testE_McpSetupExpire() throws {
        try assertRoundTrip("event", name: "mcp.setup.expire", id: nil)
    }

    func testE_McpSetupRequest() throws {
        try assertRoundTrip("event", name: "mcp.setup.request", id: nil)
    }

    func testE_MessageComplete() throws {
        try assertRoundTrip("event", name: "message.complete", id: nil)
    }

    func testE_MessageDelta() throws {
        try assertRoundTrip("event", name: "message.delta", id: nil)
    }

    func testE_MessageInterim() throws {
        try assertRoundTrip("event", name: "message.interim", id: nil)
    }

    func testE_MessageStart() throws {
        try assertRoundTrip("event", name: "message.start", id: nil)
    }

    func testE_MoaAggregating() throws {
        try assertRoundTrip("event", name: "moa.aggregating", id: nil)
    }

    func testE_MoaPhase() throws {
        try assertRoundTrip("event", name: "moa.phase", id: nil)
    }

    func testE_MoaProgress() throws {
        try assertRoundTrip("event", name: "moa.progress", id: nil)
    }

    func testE_MoaReference() throws {
        try assertRoundTrip("event", name: "moa.reference", id: nil)
    }

    func testE_Notice() throws {
        try assertRoundTrip("event", name: "notice", id: nil)
    }

    func testE_NotificationClear() throws {
        try assertRoundTrip("event", name: "notification.clear", id: nil)
    }

    func testE_NotificationShow() throws {
        try assertRoundTrip("event", name: "notification.show", id: nil)
    }

    func testE_PetGenerateProgress() throws {
        try assertRoundTrip("event", name: "pet.generate.progress", id: nil)
    }

    func testE_PetHatchProgress() throws {
        try assertRoundTrip("event", name: "pet.hatch.progress", id: nil)
    }

    func testE_PreviewActExpire() throws {
        try assertRoundTrip("event", name: "preview.act.expire", id: nil)
    }

    func testE_PreviewActRequest() throws {
        try assertRoundTrip("event", name: "preview.act.request", id: nil)
    }

    func testE_PreviewReadExpire() throws {
        try assertRoundTrip("event", name: "preview.read.expire", id: nil)
    }

    func testE_PreviewReadRequest() throws {
        try assertRoundTrip("event", name: "preview.read.request", id: nil)
    }

    func testE_PreviewRestartComplete() throws {
        try assertRoundTrip("event", name: "preview.restart.complete", id: nil)
    }

    func testE_PreviewRestartProgress() throws {
        try assertRoundTrip("event", name: "preview.restart.progress", id: nil)
    }

    func testE_Reaction() throws {
        try assertRoundTrip("event", name: "reaction", id: nil)
    }

    func testE_ReasoningAvailable() throws {
        try assertRoundTrip("event", name: "reasoning.available", id: nil)
    }

    func testE_ReasoningDelta() throws {
        try assertRoundTrip("event", name: "reasoning.delta", id: nil)
    }

    func testE_ReviewSummary() throws {
        try assertRoundTrip("event", name: "review.summary", id: nil)
    }

    func testE_SecretExpire() throws {
        try assertRoundTrip("event", name: "secret.expire", id: nil)
    }

    func testE_SecretRequest() throws {
        try assertRoundTrip("event", name: "secret.request", id: nil)
    }

    func testE_SessionInfo() throws {
        try assertRoundTrip("event", name: "session.info", id: nil)
    }

    func testE_SessionResume_progress() throws {
        try assertRoundTrip("event", name: "session.resume_progress", id: nil)
    }

    func testE_StatusUpdate() throws {
        try assertRoundTrip("event", name: "status.update", id: nil)
    }

    func testE_SudoExpire() throws {
        try assertRoundTrip("event", name: "sudo.expire", id: nil)
    }

    func testE_SudoRequest() throws {
        try assertRoundTrip("event", name: "sudo.request", id: nil)
    }

    func testE_TerminalClose() throws {
        try assertRoundTrip("event", name: "terminal.close", id: nil)
    }

    func testE_TerminalReadExpire() throws {
        try assertRoundTrip("event", name: "terminal.read.expire", id: nil)
    }

    func testE_TerminalReadRequest() throws {
        try assertRoundTrip("event", name: "terminal.read.request", id: nil)
    }

    func testE_ThinkingDelta() throws {
        try assertRoundTrip("event", name: "thinking.delta", id: nil)
    }

    func testE_ToolComplete() throws {
        try assertRoundTrip("event", name: "tool.complete", id: nil)
    }

    func testE_ToolGenerating() throws {
        try assertRoundTrip("event", name: "tool.generating", id: nil)
    }

    func testE_ToolOutput_risk() throws {
        try assertRoundTrip("event", name: "tool.output_risk", id: nil)
    }

    func testE_ToolStart() throws {
        try assertRoundTrip("event", name: "tool.start", id: nil)
    }

    func testE_TourExpire() throws {
        try assertRoundTrip("event", name: "tour.expire", id: nil)
    }

    func testE_TourRequest() throws {
        try assertRoundTrip("event", name: "tour.request", id: nil)
    }

    func testE_WakeDetected() throws {
        try assertRoundTrip("event", name: "wake.detected", id: nil)
    }

    func testE_WindowReadExpire() throws {
        try assertRoundTrip("event", name: "window.read.expire", id: nil)
    }

    func testE_WindowReadRequest() throws {
        try assertRoundTrip("event", name: "window.read.request", id: nil)
    }

}
