#!/usr/bin/env python3
"""Generate Tests/HermesKitTests/ProtocolConformanceTests.swift from
protocol/methods.json.

One deterministic round-trip test per catalog method and event: build a
minimal synthetic envelope carrying the name, encode canonically, decode,
assert equality. This is the mechanical half of G3 ("every method and event
in protocol/methods.json has a round-trip test"); the other half — golden
frames decoding and re-encoding byte-identically — lives in the checker and
WireCodecTests.

The output is COMMITTED. scripts/check_conformance.py verifies it mentions
every catalog name, so regeneration drift fails the gate.
"""
from __future__ import annotations

import json
import pathlib
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
CATALOG = REPO / "protocol" / "methods.json"
OUT = REPO / "Packages" / "HermesKit" / "Tests" / "HermesKitTests" / "ProtocolConformanceTests.swift"


def main() -> int:
    catalog = json.loads(CATALOG.read_text())
    names = ([("method", m["name"]) for m in catalog.get("requests", [])]
             + [("event", e["name"]) for e in catalog.get("events", [])])
    if not names:
        print("catalog is empty — refusing to generate a hollow suite", file=sys.stderr)
        return 1

    def swift_ident(kind: str, name: str) -> str:
        tag = "M" if kind == "method" else "E"
        cleaned = "".join(part.capitalize() for part in name.replace("-", "_").split("."))
        return f"test{tag}_{cleaned}"

    lines = [
        "// GENERATED by scripts/gen_conformance_tests.py from protocol/methods.json.",
        "// DO NOT EDIT BY HAND — regenerate instead. Coverage is enforced by",
        "// scripts/check_conformance.py (G3).",
        "",
        "import XCTest",
        "@testable import HermesKit",
        "",
        "/// One canonical round-trip per catalog entry: encode → decode → equal.",
        "final class ProtocolConformanceTests: XCTestCase {",
        "    private let codec = WireCodec()",
        "",
        "    private func assertRoundTrip(",
        "        _ kind: String, name: String, id: JSONRPCID?, file: StaticString = #filePath, line: UInt = #line",
        "    ) throws {",
        "        var envelope = JSONRPCEnvelope(method: name)",
        "        envelope.id = id",
        "        envelope.params = .object([\"__probe\": .string(name)])",
        "        let data = try codec.encode(envelope)",
        "        let decoded = try codec.decode(data)",
        "        XCTAssertEqual(decoded.method, name, \"\\(kind) \(name) lost its name\", file: file, line: line)",
        "        XCTAssertEqual(decoded.params?[\"__probe\"], .string(name), file: file, line: line)",
        "        let again = try codec.decode(try codec.encode(decoded))",
        "        XCTAssertEqual(again, decoded, \"\\(kind) \(name) not a fixed point\", file: file, line: line)",
        "    }",
        "",
    ]

    seen: set[str] = set()
    for kind, name in names:
        if name in seen:
            continue
        seen.add(name)
        ident = swift_ident(kind, name)
        if kind == "method":
            body = (f"    func {ident}() throws {{\n"
                    f"        try assertRoundTrip(\"method\", name: \"{name}\", id: .int(1))\n"
                    f"    }}\n")
        else:
            body = (f"    func {ident}() throws {{\n"
                    f"        try assertRoundTrip(\"event\", name: \"{name}\", id: nil)\n"
                    f"    }}\n")
        lines.append(body.rstrip("\n"))
        lines.append("")

    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(seen)} tests)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
